<a href="https://colab.research.google.com/github/mahepMSFT/Python/blob/master/INNHotelsGroup_of_New_data_%26_Past_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Colab notebook is opened successfully")

Colab notebook is opened successfully

In [3]:
# Installing the libraries with the specified version.
!pip install pandas==2.2.2 numpy==2.0.2 matplotlib==3.10.0 seaborn==0.13.2 scikit-learn==1.6.1 statsmodels==0.14.5 -q --user

In [5]:
# libraries to help with reading and manipulating data
import pandas as pd
import numpy as np

# libaries to help with data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# removing the limit for the number of displayed columns
pd.set_option("display.max_columns", None)
# setting the limit for the number of displayed rows
pd.set_option("display.max_rows", 200)
# setting the precision of floating numbers to 2 decimal points
pd.set_option("display.float_format", lambda x: "%.2f" % x)

# library to split data
from sklearn.model_selection import train_test_split

# library to build AI model
from sklearn.tree import DecisionTreeClassifier

# library to tune AI model
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import (
    f1_score,
    accuracy_score,
    recall_score,
    precision_score,
    confusion_matrix,
    roc_auc_score,
    ConfusionMatrixDisplay,
)

# libraries to evaluate the AI model
from sklearn.metrics import f1_score, make_scorer

# libraries to deploy the AI model
import os
import joblib

In [8]:
# defining the location where the data is stored
path = "INNHotelsGroup_pastdata.csv"
# loading the data into a Pandas dataframe
hotel = pd.read_csv(path)

In [9]:
hotel.sample(10, random_state=42)

,booking_id,lead_time,market_segment_type,no_of_special_requests,avg_price_per_room,no_of_adults,no_of_weekend_nights,arrival_date,required_car_parking_space,no_of_week_nights,booking_status,rebooked
26146,INNHG_127180,193,Offline,0,120.00,2,1,2022-06-20,0,2,Canceled,Yes
21329,INNHG_122363,34,Online,0,126.90,2,2,2022-05-01,0,1,Canceled,No
15293,INNHG_116327,9,Online,1,81.00,2,0,2022-02-17,0,1,Not Canceled,NaN
14834,INNHG_115868,4,Online,0,65.33,1,0,2022-02-09,0,3,Not Canceled,NaN
4890,INNHG_105924,320,Offline,1,115.00,2,0,2021-04-18,0,2,Canceled,No
24126,INNHG_125160,13,Online,1,149.33,2,1,2022-06-03,0,2,Not Canceled,NaN
18254,INNHG_119288,40,Online,1,139.87,3,2,2022-03-27,0,1,Canceled,No
20502,INNHG_121536,169,Offline,0,63.50,1,2,2022-04-22,0,2,Not Canceled,NaN
3843,INNHG_104877,180,Offline,2,100.08,2,1,2021-03-28,0,2,Canceled,Yes
8856,INNHG_109890,26,Online,3,124.00,2,2,2021-09-12,0,1,Not Canceled,NaN

In [10]:
# defining the location where the data is stored
path = "INNHotelsGroup_newdata.csv"
# loading the data into a Pandas dataframe
hotel = pd.read_csv(path)

In [11]:
hotel.sample(10, random_state=42)

,booking_id,lead_time,market_segment_type,no_of_special_requests,avg_price_per_room,no_of_adults,no_of_weekend_nights,arrival_date,required_car_parking_space,no_of_week_nights,booking_status
1407,INNHG_129534,142,Online,1,186.30,2,0,2022-08-03,1,3,Not Canceled
411,INNHG_128538,98,Online,1,114.30,2,0,2022-07-07,0,1,Canceled
802,INNHG_128929,140,Online,0,114.33,2,1,2022-07-18,0,3,Not Canceled
3033,INNHG_131160,35,Offline,0,85.50,2,1,2022-09-17,0,1,Not Canceled
1546,INNHG_129673,192,Online,0,99.45,2,1,2022-08-04,0,3,Canceled
554,INNHG_128681,134,Online,2,89.85,2,0,2022-07-12,0,4,Not Canceled
810,INNHG_128937,29,Online,1,144.55,2,1,2022-07-18,0,3,Not Canceled
3168,INNHG_131295,76,Offline,0,102.68,2,2,2022-09-18,0,0,Canceled
1068,INNHG_129195,190,Online,1,99.95,2,2,2022-07-24,1,2,Not Canceled
270,INNHG_128397,104,Online,1,83.12,2,0,2022-07-06,0,4,Not Canceled